# Generated by Django 2.2.16 on 2022-02-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220214_0955'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(following__isnull=True), name='fallowing_not_null'),
        ),
    ]
