# Generated by Django 2.2.16 on 2022-02-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220214_1250'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='fallowing_not_null',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(following__isnull=False), name='fallowing_not_null'),
        ),
    ]
