# Generated by Django 2.2.16 on 2022-02-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220214_1252'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='fallowing_not_null',
        ),
    ]
